n: 5
mu: 0.5
alpha: 0.4
beta: 3
t: 1000
execution: 
  - "mc"
  - "save"
  - "out"
  - "plt"
  - "bt"
dataset_dir: "/home/carlottade/Dataset_hdf5/"
outprefix: "mc_dataset"
input_file: "mc_dataset_10_100.hdf5"