n: 10
mu: 0.5
alpha: 0.8
beta: 5
t: 100
bt: 6
execution: 
  - "mc"
  - "save_mc"
  - "save_bt"
  - "out"
  - "plt"
  - "bt"
log_level: "INFO"
dataset_dir: "/home/carlottade/Dataset_hdf5/"
outprefix: "mc_dataset"
#input: "mc_dataset_0.5_0.8_5/N_10_T_100"